# Profile information
name: Smart Hacks
title: Smart Hacks - Community of developers, hackers, designers and programmers
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the community of hackers, developers, designers and programmers. Find yourself in the biggest place and grow your knowladge and experiance with us. Have fun!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.smarthacksinc.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: https://github.com/smarthacksop

# Contact form
email: smartclashcoc@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
